using System;
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "assembly", Target = "adenson.core.dll", Justification = "Not even going to bother justifing this")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "namespace", Target = "Adenson.Collections", Justification = "Not even going to bother justifing this")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Adenson.Collections.Hashtable`2.#System.Collections.Generic.ICollection`1<System.Collections.Generic.KeyValuePair`2<!0,!1>>.Contains(System.Collections.Generic.KeyValuePair`2<!0,!1>)", Justification = "Not supported")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Adenson.Collections.Hashtable`2.#System.Collections.Generic.ICollection`1<System.Collections.Generic.KeyValuePair`2<!0,!1>>.CopyTo(System.Collections.Generic.KeyValuePair`2<!0,!1>[],System.Int32)", Justification = "Not supported")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Adenson.Collections.ReadOnlyList`1")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Adenson.Collections.Set`1")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", Scope = "type", Target = "Adenson.Collections.Set`1")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "namespace", Target = "Adenson.Configuration", Justification = "Not even going to bother justifing this")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Adenson.Configuration.ConnectionStrings.#TryGet(System.String,System.Boolean,System.Configuration.ConnectionStringSettings&)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "Adenson.Configuration.EncryptorElement", Justification = "Keeping encryptor name, thank you very much")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Adenson.Configuration.EncryptorElement.#EncryptorType", MessageId = "Encryptor", Justification = "Keeping encryptor name, thank you very much")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Adenson.Configuration.LoggerSettings.#get_SeverityActual()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Adenson.Configuration.LoggerSettings.#get_TypeActual()")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope = "member", Target = "Adenson.Configuration.LoggerSettings.#Type")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "namespace", Target = "Adenson.Data", Justification = "Not even going to bother justifing this")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope = "member", Target = "Adenson.Log.LogEntry.#Type")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "namespace", Target = "Adenson.Net", Justification = "Not even going to bother justifing this")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1724:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "Adenson.Util")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:TypeNamesShouldNotMatchNamespaces", Scope = "type", Target = "Adenson.Util")]