using System;
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Adenson.Collections", Justification = "Consider another namespace, like?")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Adenson.Collections.Hashtable`2")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Adenson.Collections.Hashtable`2.#System.Collections.Generic.ICollection`1<System.Collections.Generic.KeyValuePair`2<!0,!1>>.Contains(System.Collections.Generic.KeyValuePair`2<!0,!1>)", Justification = "Not supported")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Adenson.Collections.Hashtable`2.#System.Collections.Generic.ICollection`1<System.Collections.Generic.KeyValuePair`2<!0,!1>>.CopyTo(System.Collections.Generic.KeyValuePair`2<!0,!1>[],System.Int32)", Justification = "Not supported")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Adenson.Collections.ObservableCollection`1.#.ctor(System.Collections.Generic.List`1<!0>)", Justification = "Then the inherited ObservableCollection shouldnt either!")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Adenson.Configuration.Internal.LoggerSettings.#get_SeverityActual()")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Adenson.Configuration.Internal.LoggerSettings.#get_TypeActual()")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope = "member", Target = "Adenson.Configuration.Internal.LoggerSettings.#Type")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "type", Target = "Adenson.Cryptography.DES")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Adenson.Cryptography.EncryptorType.#DES")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Adenson.Cryptography.EncryptorType.#TripleDES")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "type", Target = "Adenson.Cryptography.TripleDES")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Adenson.Cryptography.HashAlgorithmType.#MACTripleDES", MessageId = "DES")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Adenson.Cryptography.HashAlgorithmType.#MACTripleDES", MessageId = "MAC")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Adenson.Cryptography.HashAlgorithmType.#SHA512", MessageId = "SHA")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Adenson.Cryptography.HashAlgorithmType.#HMAC", MessageId = "HMAC")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Adenson.Cryptography.HashAlgorithmType.#RIPEMD160", MessageId = "RIPEMD")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Adenson.Cryptography.HashAlgorithmType.#SHA1", MessageId = "SHA")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Adenson.Cryptography.HashAlgorithmType.#SHA256", MessageId = "SHA")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "Adenson.Cryptography.HashAlgorithmType.#SHA384", MessageId = "SHA")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "type", Target = "Adenson.Data.OleDbSqlHelper")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "type", Target = "Adenson.Data.SqlCeHelper")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Adenson.FileUtil.#TryGetBytes(System.String,System.Byte[]&)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Adenson.Log", Justification = "Consider another namespace, like?")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope = "member", Target = "Adenson.Log.LogEntry.#Type")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope = "member", Target = "Adenson.Log.Logger.#Type")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Adenson.Log.Logger.#SaveToDatabase(System.Collections.Generic.List`1<Adenson.Log.LogEntry>)")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Adenson.Log.Logger.#SaveToEntryLog(System.Collections.Generic.List`1<Adenson.Log.LogEntry>)")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Adenson.Log.Logger.#SaveToFile(System.Collections.Generic.List`1<Adenson.Log.LogEntry>)")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Adenson.Log.Logger.#Write(Adenson.Log.LogSeverity,System.String,System.Object[])")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Adenson.SmtpUtil.#TrySend(System.String,System.Net.Mail.MailMessage,System.Boolean)")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames", Scope = "member", Target = "Adenson.StringUtil.#Format(System.String,System.Object[])")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1007:UseGenericsWhereAppropriate", Scope = "member", Target = "Adenson.TypeUtil.#TryConvert(System.Object,System.Type,System.Object&)")]