using System;
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "namespace", Target = "Adenson.Collections", Justification = "Not even going to bother justifing this")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Adenson.Collections.Hashtable`2.#System.Collections.Generic.ICollection`1<System.Collections.Generic.KeyValuePair`2<!0,!1>>.Contains(System.Collections.Generic.KeyValuePair`2<!0,!1>)", Justification = "Not supported")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Adenson.Collections.Hashtable`2.#System.Collections.Generic.ICollection`1<System.Collections.Generic.KeyValuePair`2<!0,!1>>.CopyTo(System.Collections.Generic.KeyValuePair`2<!0,!1>[],System.Int32)", Justification = "Not supported")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Adenson.Collections.ReadOnlyList`1")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Adenson.Collections.Set`1")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", Scope = "type", Target = "Adenson.Collections.Set`1")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "namespace", Target = "Adenson.Configuration", Justification = "Not even going to bother justifing this")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Adenson.Configuration.ConnectionStrings.#TryGet(System.String,System.Boolean,System.Configuration.ConnectionStringSettings&)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "Adenson.Configuration.EncryptorElement", Justification = "Keeping encryptor name, thank you very much")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Adenson.Configuration.EncryptorElement.#EncryptorType", MessageId = "Encryptor", Justification = "Keeping encryptor name, thank you very much")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Adenson.Configuration.LoggerSettings.#get_SeverityActual()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Adenson.Configuration.LoggerSettings.#get_TypeActual()")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope = "member", Target = "Adenson.Configuration.LoggerSettings.#Type")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1003:UseGenericEventHandlerInstances", Scope = "type", Target = "JICS.AddedEventHandler`2", Justification = "Already in use, lots of effort to change, usign generic event handler doesnt offer any gains, apart from being cumbersome looking in code.")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1010:CollectionsShouldImplementGenericInterface", Scope = "type", Target = "JICS.Configuration.FileHandlerCollection", Justification = "Too much work to implement ICollection<T> for what FileHandlerCollection is meant to do.")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope = "member", Target = "JICS.Configuration.FileHandlerElement.#Type")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope = "member", Target = "JICS.Configuration.SettingsSection.#Type")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "JICS.Configuration.Config.#TryGetSetting`1(System.String,!!0,!!0&)", Justification = "Method either succeeds or fails.")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "JICS.DataModelFactoryProvider.#NotifyChanges(JICS.IObjectChangeInfoList)", Justification = "One factory throwing an exception (regardless of what it is) should not stop the invalidation of other factories.")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "JICS.IBaseObject.#GetRelatives()")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "JICS.IComment.#SiteUrl")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "JICS.IDataModelFactory.#GetAgencies()")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "JICS.IDrawable.#GetBitmap()")]
//[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "JICS.IFile.#Physical")]
//[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "JICS.IFile.#Tags")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "JICS.IMalsChecklist.#BlankRunTime")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", Scope = "member", Target = "JICS.IMedicalEvaluation.#SpO2")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "JICS.IObjectChangeInfoList")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "JICS.IPolarizedLightMicrocopyAnalysis.#RefractiveIndices")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "JICS.IReadOnlyList`1")]
//[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "JICS.IUser.#Password")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", Scope = "member", Target = "JICS.IUser.#LastLoginDate")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope = "member", Target = "JICS.ObjectChangeInfo.#Type")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "JICS.ObjectChangeInfoList")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope = "member", Target = "JICS.ObjectQuery.#Type")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "JICS.Properties.Exceptions.resources", MessageId = "Deletable")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "JICS.Properties.Exceptions.resources", MessageId = "Xref")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1027:MarkEnumsWithFlags", Scope = "type", Target = "JICS.Resolution", Justification = "Values correspond to the actual value they represent")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces", Scope = "type", Target = "JICS.Util")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "JICS.Util.#TryGetBytes(System.String,System.Byte[]&)", Justification = "Method either succeeds or fails.")]
//[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "JICS.Serialization")]
//[assembly: SuppressMessage("Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope = "member", Target = "JICS.Serialization.ShallowRelationship.#Type")]